// Copyright 2026 momentics <momentics@gmail.com>
// Copyright libgsml3parser contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Command gsmexample runs the unified "MO call over SDCCH" demo through the Go
// binding: a BTS-side GsmL3Stack with
// AutoResponse, two MS-side UI frames built by the C typed builders, the
// orchestrator chain, and the T3101 (3 s) expiry. Stdlib only; the exit code is
// the CI contract — any failed assertion prints to stderr and exits 1.
package main

import (
	"fmt"
	"os"

	gsml3parser "github.com/momentics/libgsml3parser/bindings/go"
)

const demoTMSI = 0x87654321 // constant (SAPI 0 / profile 0 / BTS side)

// fail reports a demo assertion failure: stderr + non-zero exit (the gate contract).
func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "FAIL: "+format+"\n", args...)
	os.Exit(1)
}

func main() {
	// Both values come straight from the loaded C core (gsml3_version() ->
	// PROJECT_VERSION <- repo-root VERSION file, the single source of truth);
	// no file I/O here.
	fmt.Printf("version %s  (C ABI revision %d)\n", gsml3parser.Version(), gsml3parser.ABIVersion())

	// BTS-side stack: registry + borrowed session + orchestrator + LAPDm entity
	// with the C->Go bridges; AutoResponse=true drives parse -> feed ->
	// required_size -> build_response -> send_ui inside each SendFrame, all
	// AFTER the C call returned (queue model).
	stack, err := gsml3parser.NewGsmL3Stack(gsml3parser.StackOptions{
		TMSI:         demoTMSI,
		SAPI:         0, // SDCCH
		Profile:      0, // SDCCH profile (T200 = 900 ms)
		AutoResponse: true,
	})
	if err != nil {
		fail("stack init: %v", err)
	}
	defer stack.Close()

	// -- [1] CMServiceRequest (MO call) ---------------------------------------
	// L3 is generated by a C typed builder (no hardcoded wire constants); the MS
	// side wraps it into a UI frame (C/R=0, SAPI 0) with the mini-codec.
	l3, err := gsml3parser.BuildCMServiceRequest(1 /*MobileOriginatedCall*/, gsml3parser.IDTMSI, demoTMSI, "")
	if err != nil {
		fail("build cm_service_request: %v", err)
	}
	txs, err := stack.SendFrame(gsml3parser.UIFrame(0, false, l3))
	if err != nil {
		fail("send_frame(ui CMServiceRequest): %v", err)
	}
	if len(txs) != 1 {
		fail("[1] expected exactly one auto-response frame, got %d", len(txs))
	}
	step, ok := stack.LastStep()
	if !ok || step.Token != gsml3parser.TokenCMServiceAccept {
		fail("[1] expected token %d (CM_SERVICE_ACCEPT), got %+v (present=%v)", gsml3parser.TokenCMServiceAccept, step, ok)
	}
	fmt.Printf("[1] CMServiceRequest -> token=%d (CM_SERVICE_ACCEPT)\n", step.Token)

	// The response is a BTS-side UI (C/R=1): verify the payload via the C
	// zero-copy decoder — its view sits INSIDE txs[0].
	dec, err := gsml3parser.DecodeFrame(txs[0])
	if err != nil {
		fail("decode response frame: %v", err)
	}
	if dec.Format != gsml3parser.LapdmFmtU || dec.UType != gsml3parser.LapdmUUI || dec.SAPI != 0 || dec.Command != 1 {
		fail("[1] response decode = (fmt %d, u %#x, sapi %d, cmd %d), want U/UI/0/BTS", dec.Format, dec.UType, dec.SAPI, dec.Command)
	}
	resp, err := gsml3parser.Parse(dec.Payload, nil)
	if err != nil {
		fail("parse response payload: %v", err)
	}
	defer resp.Close()
	if resp.Name() != "CMServiceAccept" || resp.Pd() != gsml3parser.PDMM {
		fail("[1] response name/pd = %q/%d, want CMServiceAccept/MM", resp.Name(), resp.Pd())
	}
	respHex, err := resp.Hex()
	if err != nil {
		fail("response hex: %v", err)
	}
	size, _ := resp.Size()
	fmt.Printf("[1] response: %s (%d bytes): %s\n", resp.Name(), size, respHex)

	// -- [2] CC Setup (TI=3, called 123456789) -> CallProceeding ---------------
	l3s, err := gsml3parser.BuildSetup(3, "123456789")
	if err != nil {
		fail("build setup: %v", err)
	}
	txs, err = stack.SendFrame(gsml3parser.UIFrame(0, false, l3s))
	if err != nil {
		fail("send_frame(ui Setup): %v", err)
	}
	if len(txs) != 1 {
		fail("[2] expected exactly one auto-response frame, got %d", len(txs))
	}
	step, ok = stack.LastStep()
	if !ok || step.Token != gsml3parser.TokenCallProceeding {
		fail("[2] expected token %d (CALL_PROCEEDING), got %+v (present=%v)", gsml3parser.TokenCallProceeding, step, ok)
	}
	fmt.Printf("[2] Setup -> token=%d (CALL_PROCEEDING)\n", step.Token)
	cpDec, err := gsml3parser.DecodeFrame(txs[0])
	if err != nil {
		fail("decode CallProceeding frame: %v", err)
	}
	cp, err := gsml3parser.Parse(cpDec.Payload, nil)
	if err != nil {
		fail("parse CallProceeding: %v", err)
	}
	defer cp.Close()
	if cp.Name() != "CallProceeding" || cp.Ti() != 3 {
		fail("[2] call proceeding name/ti = %q/%d, want CallProceeding/3", cp.Name(), cp.Ti())
	}

	phase, err := stack.ChainPhase()
	if err != nil {
		fail("chain phase: %v", err)
	}
	if phase != gsml3parser.ProcCallSetupMO {
		fail("[2] chain phase = %#x, want GSML3_PROC_CALL_SETUP_MO(0x%#x)", phase, gsml3parser.ProcCallSetupMO)
	}
	fmt.Printf("[2] chain phase = %d (GSML3_PROC_CALL_SETUP_MO)\n", phase)

	// -- [3] T3101 = 3 s: inside the window nothing fails; expiry times the ──
	//      chain out and resets it to idle (chain timers, entity T200 is covered
	//      by the tests).
	n0, err := stack.TickProcedures(1000)
	if err != nil || n0 != 0 {
		fail("[3] tick_procedures(1000 ms) = (%d, %v), want (0, nil) — inside the T3101 window", n0, err)
	}
	retr, err := stack.TakeRetransmit()
	if err != nil || retr != gsml3parser.TokenNone {
		fail("[3] take_retransmit = (%d, %v), want (NONE, nil)", retr, err)
	}
	fmt.Printf("[3] T3101 window: tick(1000 ms) failures=%d, retransmit=NONE\n", n0)

	n1, err := stack.TickProcedures(2500) // cumulative 3500 ms > 3000 ms
	if err != nil || n1 != 1 {
		fail("[3] tick_procedures(2500 ms) = (%d, %v), want (1, nil) — T3101 expired", n1, err)
	}
	phase, err = stack.ChainPhase()
	if err != nil || phase != gsml3parser.ProcUnknown {
		fail("[3] chain after expiry = %#x (err %v), want GSML3_PROC_UNKNOWN(0xFF)", phase, err)
	}
	fmt.Printf("[3] T3101 expired: tick(+2500 ms) failures=%d, chain phase = %d (GSML3_PROC_UNKNOWN)\n", n1, phase)

	if err := stack.Close(); err != nil {
		fail("stack close: %v", err)
	}
	fmt.Println("OK: MO-call simulation completed (all steps asserted).")
}
