# Copyright 2026 momentics <momentics@gmail.com>
# Copyright libgsml3parser contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""PEP 517 build backend for the ``gsml3parser`` package.

The product version has exactly one source of truth: the ``VERSION`` file at
the repository root (one semver ``X.Y.Z`` line, two directory levels above
this file: ``bindings/python`` -> ``bindings`` -> repository root). Setuptools
can only read dynamic-version sources from inside the project directory, so
this shim performs that single step itself — every hook below materializes
the version into ``gsml3parser/_version.py`` and then delegates unchanged to
``setuptools.build_meta``. The generated module is stamped into the package
metadata by pyproject.toml and ships inside every sdist and wheel; no other
file in this project carries a copy of the product version, so no build can
drift from the VERSION file.

The shim itself requires only the Python standard library; setuptools is
provided by ``[build-system] requires``.
"""

from __future__ import annotations

import pathlib
import re

from setuptools import build_meta as _setuptools

_PROJECT = pathlib.Path(__file__).resolve().parent
_VERSION_FILE = _PROJECT.parent.parent / "VERSION"
_GENERATED_MODULE = _PROJECT / "gsml3parser" / "_version.py"
_SEMVER_RE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")


def _product_version() -> str:
    raw = _VERSION_FILE.read_text(encoding="utf-8").strip()
    if not _SEMVER_RE.match(raw):
        raise RuntimeError(
            f"{_VERSION_FILE} must contain a single semver X.Y.Z line, got {raw!r}")
    return raw


def _materialize_version() -> None:
    """Write the build-time version module before delegating (idempotent)."""
    payload = (
        "# Auto-generated by build_backend.py from the repository-root "
        "VERSION file.\n"
        "# Do not edit by hand; it is rewritten at packaging time.\n"
        f'__version__ = "{_product_version()}"\n'
    )
    try:
        current = _GENERATED_MODULE.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current != payload:
        _GENERATED_MODULE.write_text(payload, encoding="utf-8")


# ── PEP 517 hooks: version first, then plain delegation to setuptools ──────

def get_requires_for_build_wheel(config_settings=None):
    # Config parsing happens during delegation and resolves the dynamic
    # version attr — materialize it first.
    _materialize_version()
    return _setuptools.get_requires_for_build_wheel(config_settings)


def get_requires_for_build_sdist(config_settings=None):
    _materialize_version()
    return _setuptools.get_requires_for_build_sdist(config_settings)


def prepare_metadata_for_build_wheel(metadata_directory, config_settings=None):
    _materialize_version()
    return _setuptools.prepare_metadata_for_build_wheel(metadata_directory, config_settings)


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    _materialize_version()
    return _setuptools.build_wheel(wheel_directory, config_settings, metadata_directory)


def build_sdist(sdist_directory, config_settings=None):
    _materialize_version()
    return _setuptools.build_sdist(sdist_directory, config_settings)


# Editable installs: delegate if the setuptools version provides the hooks.
if hasattr(_setuptools, "build_editable"):

    def get_requires_for_build_editable(config_settings=None):
        _materialize_version()
        return _setuptools.get_requires_for_build_editable(config_settings)

    def build_editable(wheel_directory, config_settings=None, metadata_directory=None):
        _materialize_version()
        return _setuptools.build_editable(
            wheel_directory, config_settings, metadata_directory)
