// Copyright 2026 momentics <momentics@gmail.com>
// Copyright libgsml3parser contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//! MO call over SDCCH — the unified demo scenario shared by all three bindings
//! (identical behavioral vectors to the Python /
//! Go examples and to `TEST(CApiOrchestrator, MOCallSetupChain)`): a BTS-side
//! `GsmL3Stack` with auto-response, two MS-side UI frames built by the C typed
//! builders (`gsml3_build_cm_service_request` / `gsml3_build_setup`) plus the
//! Rust mini-codec, the orchestrator chain (CMServiceRequest → accept token 10;
//! Setup → call proceeding token 17; chain phase CALL_SETUP_MO), and the
//! T3101 (3 s) chain-timer expiry back to idle. The exit code is the CI
//! contract: any failed check prints `FAIL: …` to stderr and exits 1.

use std::process::exit;

use gsml3parser::lapdm::{decode_frame, mini};
use gsml3parser::{build_cm_service_request, build_setup, version, GsmL3Stack, Message};
use gsml3parser_sys as sys; // raw constants (GSML3_TOKEN_* etc.) for readable asserts

const DEMO_TMSI: u32 = 0x8765_4321; // the demo scenario constant (SAPI 0 / profile 0 / BTS side)

/// Report a demo failure: stderr + exit code 1 (the unified-gate contract).
fn fail(what: String) -> ! {
    eprintln!("FAIL: {what}");
    exit(1);
}

/// Assert helper: if `ok` is false → FAIL with the message. The message may be
/// a plain &str or a `format!(…)` String — it is evaluated only when the check
/// actually fails (it lives in the failure branch).
macro_rules! check {
    ($ok:expr, $msg:expr) => {
        if !$ok {
            fail($msg.to_string())
        }
    };
}

fn run() -> Result<(), String> {
    // Both values come straight from the loaded C core (gsml3_version() →
    // PROJECT_VERSION → the repo-root VERSION file) — no file I/O here.
    let abi = gsml3parser::abi_version();
    check!(
        sys::ABI_VERSION == abi && abi == 1,
        format!("ABI version mismatch: sys={} core={abi}", sys::ABI_VERSION)
    );
    println!("version {v}  (C ABI revision {abi})", v = version());

    // BTS-side stack: registry + borrowed session + orchestrator + LAPDm entity
    // with the C→Rust trampolines; auto_response=true drives parse → feed →
    // required_size → build_response → send_ui inside each send_frame, all
    // AFTER the C call returned (queue model).
    let mut stack = GsmL3Stack::new(DEMO_TMSI, 0, 0 /* SAPI 0: SDCCH */, 0 /* profile 0: T200=900 ms */, true)
        .map_err(|e| format!("stack init: {e}"))?;

    // -- [1] CMServiceRequest (MO call) -------------------------------------
    // L3 is generated by the C typed builder (no hardcoded wire constants); the
    // MS side wraps it into a UI frame (C/R=0, SAPI 0) with the mini-codec.
    let l3 = build_cm_service_request(1 /* MobileOriginatedCall */, sys::GSML3_ID_TMSI, DEMO_TMSI, None)
        .map_err(|e| format!("build_cm_service_request: {e}"))?;
    let frame = mini::ui(0, false, &l3).map_err(|e| format!("mini ui: {e}"))?;
    let txs = stack.send_frame(&frame).map_err(|e| format!("send_frame(ui CMServiceRequest): {e}"))?;
    check!(
        txs.len() == 1,
        format!("[1] expected exactly one auto-response frame, got {}", txs.len())
    );

    let step = stack
        .last_step()
        .ok_or_else(|| "[1] no orchestrator step was recorded".to_string())?;
    check!(
        step.token == sys::GSML3_TOKEN_CM_SERVICE_ACCEPT,
        format!(
            "[1] expected token {} (CM_SERVICE_ACCEPT), got {}",
            sys::GSML3_TOKEN_CM_SERVICE_ACCEPT, step.token
        )
    );
    println!("[1] CMServiceRequest -> token={} (CM_SERVICE_ACCEPT)", step.token);

    // The response is a BTS-side UI (C/R=1): verify it with the C zero-copy
    // decoder — the payload view must sit INSIDE txs[0] (no intermediate copy).
    let dec = decode_frame(&txs[0]).map_err(|e| format!("decode response frame: {e}"))?;
    check!(
        (dec.format, dec.u_type, dec.sapi, dec.command)
            == (sys::GSML3_LAPDM_FMT_U, sys::GSML3_LAPDM_U_UI, 0, 1),
        format!(
            "[1] response decode = (fmt {}, u {:#x}, sapi {}, cmd {}), want U/UI/0/BTS",
            dec.format, dec.u_type, dec.sapi, dec.command
        )
    );
    let payload = dec.payload.ok_or_else(|| "[1] the auto-response UI carries no payload".to_string())?;
    // Zero-copy check: the decoder's payload view must alias txs[0] (address math
    // only — a pointer→usize conversion performs no arithmetic, so it is safe
    // regardless of where the C decoder actually pointed).
    let start = txs[0].as_ptr() as usize;
    let end = start + txs[0].len();
    let info_addr = payload.as_ptr() as usize;
    if !(info_addr >= start && info_addr <= end) {
        fail("[1] zero-copy check failed: the decoded payload does not alias txs[0]".into());
    }
    check!(
        info_addr - start + payload.len() <= txs[0].len(),
        "[1] zero-copy view escaped the frame buffer"
    );

    let resp = Message::parse(payload, None).map_err(|e| format!("parse response payload: {e}"))?;
    check!(
        resp.name().as_deref() == Ok("CMServiceAccept"),
        format!("[1] response name is not CMServiceAccept: {:?}", resp.name())
    );
    check!(resp.pd()? == sys::GSML3_PD_MM, "[1] response pd is not MM");
    let hex = resp.hex_str().map_err(|e| format!("response hex: {e}"))?;
    println!("[1] response: {} ({} bytes): {}", resp.name()?, resp.size()?, hex);

    // -- [2] CC Setup (TI=3, called 123456789) → CallProceeding -------------
    let l3s = build_setup(3, "123456789").map_err(|e| format!("build_setup: {e}"))?;
    let frame_s = mini::ui(0, false, &l3s).map_err(|e| format!("mini ui: {e}"))?;
    let txs = stack.send_frame(&frame_s).map_err(|e| format!("send_frame(ui Setup): {e}"))?;
    check!(
        txs.len() == 1,
        format!("[2] expected exactly one auto-response frame, got {}", txs.len())
    );
    let step = stack
        .last_step()
        .ok_or_else(|| "[2] no orchestrator step was recorded".to_string())?;
    check!(
        step.token == sys::GSML3_TOKEN_CALL_PROCEEDING,
        format!(
            "[2] expected token {} (CALL_PROCEEDING), got {}",
            sys::GSML3_TOKEN_CALL_PROCEEDING, step.token
        )
    );
    println!("[2] Setup -> token={} (CALL_PROCEEDING)", step.token);
    let cp_dec = decode_frame(&txs[0]).map_err(|e| format!("decode CallProceeding frame: {e}"))?;
    let cp = Message::parse(cp_dec.payload.ok_or("no CallProceeding payload")?, None)
        .map_err(|e| format!("parse CallProceeding: {e}"))?;
    check!(
        cp.name().as_deref() == Ok("CallProceeding"),
        format!("[2] response name is not CallProceeding: {:?}", cp.name())
    );
    check!(cp.ti()? == 3, format!("[2] call proceeding TI = {}, want 3", cp.ti()?));

    let phase = stack.chain_phase().map_err(|e| format!("chain phase: {e}"))?;
    check!(
        phase == sys::GSML3_PROC_CALL_SETUP_MO,
        format!("[2] chain phase = {phase:#x}, want CALL_SETUP_MO (0x04)")
    );
    println!("[2] chain phase = {phase} (GSML3_PROC_CALL_SETUP_MO)");

    // -- [3] T3101 = 3 s: inside the window nothing fails; expiry times the ──
    //      chain out and resets it to idle (chain timers — the entity T200 is
    //      covered by the tests, this exercises gsml3_orchestrator_tick).
    let n0 = stack.tick_procedures(1000).map_err(|e| format!("tick_procedures: {e}"))?;
    check!(n0 == 0, format!("[3] tick_procedures(1000 ms) = {n0}, want 0 (inside the T3101 window)"));
    let retr = stack.take_retransmit().map_err(|e| format!("take_retransmit: {e}"))?;
    check!(retr == sys::GSML3_TOKEN_NONE, format!("[3] take_retransmit = {retr}, want NONE"));
    println!("[3] T3101 window: tick(1000 ms) failures={n0}, retransmit=NONE");

    let n1 = stack.tick_procedures(2500).map_err(|e| format!("tick_procedures: {e}"))?; // cumulative 3500 > 3000
    check!(n1 == 1, format!("[3] tick_procedures(+2500 ms) = {n1}, want 1 (T3101 expired)"));
    let phase = stack.chain_phase().map_err(|e| format!("chain phase: {e}"))?;
    check!(
        phase == sys::GSML3_PROC_UNKNOWN,
        format!("[3] chain after expiry = {phase:#x}, want GSML3_PROC_UNKNOWN (0xFF)")
    );
    println!("[3] T3101 expired: tick(+2500 ms) failures={n1}, chain phase = {phase} (GSML3_PROC_UNKNOWN)");

    // Teardown in the C ABI order entity → orchestrator → registry (the
    // borrowed session is never freed directly — it goes with the registry).
    stack.close();
    Ok(())
}

fn main() {
    match run() {
        Ok(()) => println!("OK: MO-call simulation completed (all steps asserted)."),
        Err(e) => fail(e),
    }
}
