// Copyright 2026 momentics <momentics@gmail.com>
// Copyright libgsml3parser contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/// Procedure orchestrator for chained GSM L3 protocol procedures.
///
/// Manages compound procedure chains such as Location Update
/// (CMServiceRequest -> Identity -> Authentication -> CipheringMode -> LocationUpdate)
/// and Call Setup MO (CMServiceRequest -> CallSetupMO). The orchestrator owns a single
/// active Procedure at any time, transitions between phases based on procedure outcomes,
/// and updates the SubscriberSession FSM states to stay in sync.
///
/// Does NOT store ParsedMessage (~8KB variant) internally. Instead stores the last
/// ResponseToken and provides buildPendingResponse() for zero-allocation response building.
/// This is critical for high-load BTS: avoids heap allocation per response.
///
/// 3GPP TS 24.008 - Compound procedure chains (Location Update, Call Setup).
/// Thread safety: NOT thread-safe. One instance per subscriber chain.
/// Memory: No heap allocations during feed() path; uses unique_ptr for current procedure.
///
/// Example:
/// @code
///   ProcedureOrchestrator orchestrator;
///   auto result = orchestrator.feed(incomingMsg, session);
///   if (result.action == ProcedureStepResult::Action::SendResponseWithToken) {
///       int n = orchestrator.buildPendingResponse(arenaBuffer, session);
///       sendToRadio(arenaBuffer.data(), n);
///   }
/// @endcode
#pragma once

#include <chrono>
#include <cstdint>
#include <memory>
#include <span>

#include "gsml3parser/stack/l3_timer.h"
#include "gsml3parser/stack/procedure.h"
#include "gsml3parser/stack/procedure_types.h"
#include "gsml3parser/stack/typed_external_data.h"

namespace gsml3parser {

class SubscriberSession;

/// Orchestrates chains of protocol procedures for compound L3 transactions.
class ProcedureOrchestrator {
public:
    ProcedureOrchestrator() = default;

    /// Feed an incoming L3 message into the active chain.
    /// @param msg The parsed L3 message from the MS.
    /// @param session Pointer to subscriber session for context and FSM updates.
    /// @return ProcedureStepResult with action, responseToken, and finalResult.
    [[nodiscard]] ProcedureStepResult feed(const ParsedMessage& msg, SubscriberSession* session);

    /// Feed typed external data into the active chain.
    /// @param data Strongly-typed external data (AuthChallenge, VLRDecision, etc.).
    /// @param sink Optional response callback.
    /// @return ProcedureStepResult from the active procedure or phase handler.
    [[nodiscard]] ProcedureStepResult feedExternalTyped(const ExternalData& data, ResponseSink sink = {});

    /// Tick all timers for the active chain: the active Procedure's own timer
    /// and the phase timer of inline phases (T3103 while the LocationUpdate
    /// phase waits for the VLR decision). A phase-timer expiry cancels the
    /// whole chain and is reported as one failure.
    /// @param delta Elapsed time in milliseconds.
    /// @return Number of failures (procedure timeout and/or phase-timer expiry).
    size_t tickAll(std::chrono::milliseconds delta);

    /// Cancel all active procedures in the chain.
    void cancelAll() noexcept;

    /// Get the current active procedure, or nullptr if in an inline phase.
    [[nodiscard]] Procedure* activeProcedure() noexcept;
    [[nodiscard]] const Procedure* activeProcedure() const noexcept;

    /// Get the last response token generated by the chain.
    [[nodiscard]] ResponseToken lastResponseToken() const noexcept;

    /// Build the pending response into a pre-allocated buffer (zero heap allocation).
    /// @param out Pre-allocated output buffer (Arena-provided).
    /// @param session Optional session context for parameters.
    /// @return Number of bytes written, or -1 on error.
    [[nodiscard]] int buildPendingResponse(std::span<uint8_t> out,
                                            const SubscriberSession* session) const;

    /// Get the current chain phase.
    [[nodiscard]] procedure::ProcedureType chainPhase() const noexcept;

private:
    enum class ChainPhase : uint8_t {
        None,
        CMServiceRequest,
        IdentityVerification,
        Authentication,
        CipheringMode,
        LocationUpdate,
        CallSetupMO,
        CallSetupMT,
        ChannelAssignment,
        Paging,
        Handover,
        IMSIDetach,
        PeriodicLocationUpdate,
        CallRelease
    };

    ChainPhase mCurrentPhase{ChainPhase::None};
    std::unique_ptr<Procedure> mCurrentProcedure;
    SubscriberSession* mSession{nullptr};
    ResponseToken mLastToken{ResponseToken::None};
    procedure::ProcedureType mChainType{procedure::ProcedureType::Unknown};

    // Phase timer for inline phases (no Procedure object to carry its own
    // timer). Started in transitionToPhase() for LocationUpdate (T3103, 5s);
    // expiry in tickAll() cancels the chain. Stopped by cancelAll(), on phase
    // completion, and on any transition out of the timed phase.
    L3TimerId mPhaseTimer{L3TimerId::Unknown};
    std::chrono::milliseconds mPhaseTimerRemaining{0};
    bool mPhaseTimerRunning{false};

    void transitionToPhase(ChainPhase phase);
    void stopPhaseTimer() noexcept;
    std::unique_ptr<Procedure> createProcedureForPhase(ChainPhase phase);
    void onProcedureCompleted(const ProcedureStepResult& result);
    void onProcedureFailed(const ProcedureStepResult& result);

    // Inline phase handlers (no Procedure object needed)
    [[nodiscard]] ProcedureStepResult handleCMServiceRequest(const ParsedMessage& msg, SubscriberSession* session);
    [[nodiscard]] ProcedureStepResult handleIdentityVerification(const ParsedMessage& msg, SubscriberSession* session);
    [[nodiscard]] ProcedureStepResult handleLocationUpdatePhase(const ParsedMessage& msg, SubscriberSession* session);
    [[nodiscard]] ProcedureStepResult handleIMSIDetachPhase(const ParsedMessage& msg, SubscriberSession* session);
    [[nodiscard]] ProcedureStepResult handleCallReleasePhase(const ParsedMessage& msg, SubscriberSession* session);

    // External data handlers for inline phases
    [[nodiscard]] ProcedureStepResult handleExternalDataLocationUpdate(const ExternalData& data, ResponseSink sink);
    [[nodiscard]] ProcedureStepResult handleExternalDataIMSIDetach(const ExternalData& data, ResponseSink sink);
    [[nodiscard]] ProcedureStepResult handleExternalDataCallRelease(const ExternalData& data, ResponseSink sink);

    // Detect chain type from incoming message
    [[nodiscard]] ChainPhase detectChainPhase(const ParsedMessage& msg) const;
};

} // namespace gsml3parser
