# Copyright 2026 momentics <momentics@gmail.com>
# Copyright libgsml3parser contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Simulation tests: MO call over SDCCH with auto-response orchestration from
the C core callbacks, LAPDm link lifecycle (byte-exact SABME/UA vectors
mirroring the C Entity_LinkLifecycle test), T200 retransmission, wrapper-level
NULL policy, and the sharded-registry smoke.

Vectors are stable / generated by C builders at test time (decision #12): the
demo chain is built with build_cm_service_request / build_setup and expected
values mirror tests/test_c_api.cpp (tokens 10/17, names, phases, T3101 = 3 s,
T200(SDCCH) = 900 ms).
"""

import ctypes

import pytest

from gsml3parser import _library
import gsml3parser as g

TMSI = 0x87654321


# ── MO call simulation ─────────────────────────────────────────────────────

def stack_mo_call_simulation():
    """Full demo scenario in MANUAL orchestration (auto_response=False): the L3
    queue stays unprocessed after each C call; we drain, feed and send — proving
    the whole surface and every intermediate StepResult.

    1) CMServiceRequest(service_type=1 MobileOriginatedCall, TMSI identity)
       -> token CM_SERVICE_ACCEPT(10), auto-response built from required_size;
    2) CC Setup (TI=3, called '123456789') -> token CALL_PROCEEDING(17),
       chain phase GSML3_PROC_CALL_SETUP_MO(0x04);
    3) T3101 = 3 s: tick(1000 ms) no failures, tick(2500 ms) expiry fails the
       chain and resets it to idle (GSML3_PROC_UNKNOWN=0xFF)."""
    with g.GsmL3Stack(tmsi=TMSI, auto_response=False) as stack:
        assert stack.tmsi == TMSI

        # -- step 1 -----------------------------------------------------------------
        l3 = g.build_cm_service_request(service_type=1, id_type=g.ID_TMSI, tmsi=TMSI, imsi=None)
        ui_ms = g.lapdm_mini.ui(sapi=0, command=False, info=l3)   # MS -> BTS UI (C/R=0)
        txs = stack.send_frame(ui_ms)
        assert txs == []                     # L2 emits nothing; the chain runs in step 4 below
        evs = stack.drain_l3_events()
        assert len(evs) == 1
        ev = evs[0]
        assert ev.sapi == 0 and ev.primitive == g.PRIM_L3_UNIT_DATA == 4
        assert ev.data == l3                 # the bridge delivered an owned COPY of the span
        step1 = stack.feed_l3(ev.data)
        assert step1.token == g.TOKEN_CM_SERVICE_ACCEPT == 10
        resp1 = stack.build_response()       # required_size -> exact-size build (decision #8)
        txs = stack.send_ui(resp1)           # manual transmit; captured by the L1 bridge
        assert len(txs) == 1
        dec = g.lapdm_frame_decode(txs[0])   # cross-check with the C decoder
        assert (dec.format, dec.u_type, dec.sapi, dec.command) == (2, 3, 0, 1)
        assert dec.info_offset is not None and dec.info_offset >= 2
        # zero-copy proof: the C decoder's info view sat INSIDE txs[0] at that offset
        assert txs[0][dec.info_offset:dec.info_offset + dec.info_len] == dec.info == resp1
        acc = g.Message.from_bytes(dec.info)
        try:
            assert acc.name == "CMServiceAccept" and acc.pd == g.PD_MM == 5
        finally:
            acc.close()

        # -- step 2 -----------------------------------------------------------------
        l3s = g.build_setup(ti=3, called_digits="123456789")
        txs = stack.send_frame(g.lapdm_mini.ui(sapi=0, command=False, info=l3s))
        evs = stack.drain_l3_events()
        assert len(evs) == 1 and evs[0].data == l3s
        step2 = stack.feed_l3(evs[0].data)
        assert step2.token == g.TOKEN_CALL_PROCEEDING == 17 != g.TOKEN_NONE
        resp2 = stack.build_response()
        txs = stack.send_ui(resp2)
        assert len(txs) == 1
        cp = g.Message.from_bytes(g.lapdm_frame_decode(txs[0]).info)
        try:
            assert cp.name == "CallProceeding" and cp.ti == 3
        finally:
            cp.close()
        assert stack.chain_phase == g.PROC_CALL_SETUP_MO == 0x04

        # -- step 3: T3101 = 3 s ----------------------------------------------------
        assert stack.tick_procedures(1000) == 0      # inside the window
        assert stack.take_retransmit() == g.TOKEN_NONE
        assert stack.tick_procedures(2500) == 1      # expiry: one procedure failure
        assert stack.chain_phase == g.PROC_UNKNOWN   # chain reset to idle


def test_stack_auto_response_mode():
    """Default mode (auto_response=True): send_frame drains the L3 queue AFTER
    the C call returned, feeds, builds the required-size response and transmits
    it — one tx frame per MO request, nothing left in the queues."""
    with g.GsmL3Stack(tmsi=0x33333333) as stack:    # auto_response=True default
        l3 = g.build_cm_service_request(1, g.ID_TMSI, 0x33333333, None)
        txs = stack.send_frame(g.lapdm_mini.ui(0, False, l3))
        assert len(txs) == 1 and stack.last_step.token == 10
        dec = g.lapdm_frame_decode(txs[0])
        assert dec.command == 1                      # BTS-side frame (C/R=1)
        assert g.Message.from_bytes(dec.info).name == "CMServiceAccept"
        assert stack.drain_l3_events() == []         # queue consumed post-FFI
        assert stack.drain_tx_frames() == []


# ── Link lifecycle + T200 (mirrors C TEST(CApi, Entity_LinkLifecycle)) ────

def stack_link_lifecycle():
    """Standalone entity (BTS side, C/R=1) driven by the mini-codec peer frames:
    open -> LINK_RELEASED; SABME -> tx [0x09, 0x2F] (byte-exact), state AWAITING_
    ESTABLISH; peer UA [0x01, 0x63] -> LINK_ESTABLISHED (+ ESTABLISH_CONFIRM L3
    event, empty payload); UI with L3 -> UNIT_DATA event with the SAME payload;
    DISC -> AWAITING_RELEASE; peer UA -> LINK_RELEASED. frames_received() == 3."""
    events, txs = [], []

    def on_l3(sapi, prim, l3p, l3_len, user):
        data = ctypes.string_at(l3p, l3_len) if (l3p is not None and l3_len > 0) else b""
        events.append((int(prim), bytes(data)))

    def on_l1(frame, frame_len, user):
        txs.append(bytes(ctypes.string_at(frame, frame_len)) if (frame is not None and frame_len > 0) else b"")

    with g.LapdmEntity(profile=0, l3_cb=on_l3, l1_cb=on_l1) as e:   # 0 = SDCCH
        assert e.state() == g.LAPDM_STATE_UNUSED
        e.open(sapi=0, command_bit=1)                               # BTS side
        assert e.state() == g.LAPDM_STATE_LINK_RELEASED
        e.send_sabme()
        assert txs and txs[-1] == bytes([0x09, 0x2F])               # SABME from BTS (byte-exact)
        assert e.state() == g.LAPDM_STATE_AWAITING_ESTABLISH
        e.receive(bytes([0x01, 0x63]))                              # MS -> UA
        assert e.state() == g.LAPDM_STATE_LINK_ESTABLISHED and e.is_established()

        payload = b"\x60\x0d\x00"                                   # Channel Release L3
        e.receive(g.lapdm_mini.ui(sapi=0, command=False, info=payload))
        e.send_disc()
        assert e.state() == g.LAPDM_STATE_AWAITING_RELEASE
        e.receive(bytes([0x01, 0x63]))                              # MS -> UA (release ack)
        assert e.state() == g.LAPDM_STATE_LINK_RELEASED and not e.is_established()
        frames_rx = e.frames_received()

    # the entity is closed now (any accessor would raise); verify captured values
    assert frames_rx == 3
    assert events[0] == (g.PRIM_L3_ESTABLISH_CONFIRM, b"")
    assert any(ev == (g.PRIM_L3_UNIT_DATA, payload) for ev in events)


def t200_retransmission():
    """SDCCH profile: T200 = 900 ms. Two independent entities keep the
    semantics unambiguous (no timer-accumulation assumption):
      * inside the window (899 ms) — no retransmission, counter stays 0;
      * at exactly 900 ms — return 1, counter reaches 1, a fresh byte-exact
        SABME tx frame is emitted (mirrors the C Entity_LinkLifecycle test)."""
    def make_tx_capture():
        txs = []
        def on_l1(frame, frame_len, user):
            if frame is not None and frame_len > 0:
                txs.append(bytes(ctypes.string_at(frame, frame_len)))
        return txs, on_l1

    # inside the window
    _, on_l1 = make_tx_capture()
    with g.LapdmEntity(profile=0, l1_cb=on_l1) as e:
        e.open(sapi=0, command_bit=1)
        e.send_sabme()
        assert e.tick_t200(899) == 0
        assert e.retransmissions() == 0

    # exactly at expiry
    txs, on_l1 = make_tx_capture()
    with g.LapdmEntity(profile=0, l1_cb=on_l1) as e:
        e.open(sapi=0, command_bit=1)
        e.send_sabme()
        assert len(txs) == 1 and txs[0] == bytes([0x09, 0x2F])   # first SABME
        r = e.tick_t200(900)                                     # crosses T200(SDCCH)
        assert r == 1 and e.retransmissions() == 1
        assert len(txs) == 2 and txs[1] == bytes([0x09, 0x2F])   # retransmitted SABME


def frames_received_counting():
    """The statistic counter counts L1 frames actually received by the FSM."""
    txs = []
    with g.LapdmEntity(0, l1_cb=lambda f, fl, u: None) as e:
        e.open(0, 1)
        assert e.frames_received() == 0
        e.send_sabme()
        e.receive(bytes([0x01, 0x63]))      # UA (establish)
        assert e.frames_received() == 1
        e.receive(bytes([0x01, 0x5F]))      # UA (pf=0 variant — also accepted by C decode)
        e.receive(bytes([0x01, 0x63]))      # another UA
        assert e.frames_received() == 3


# ── NULL policy at the wrapper level ──────────────────────────────────────

def null_safety_stack_level():
    """Wrapper-level rejections happen BEFORE the FFI boundary (verified via the
    _library.CALL_COUNTS seam); C-owned validation errors are passed through as
    typed GsmL3Errors with their last-error message."""
    with g.GsmL3Stack(tmsi=0x44444444, auto_response=False) as stack:
        base = _library.CALL_COUNTS.get("gsml3_lapdm_entity_receive", 0)
        with pytest.raises(TypeError):
            stack.send_frame(None)                       # null-ish input: TypeError pre-FFI
        with pytest.raises(ValueError):
            stack.send_frame(b"")                        # too short (< address + control)
        assert _library.CALL_COUNTS.get("gsml3_lapdm_entity_receive", 0) == base   # no FFI at all

    # all-zero TMSI is a C-side rule (TS 24.008) — passed through, message copied
    with pytest.raises(g.GsmL3Error) as exc:
        g.GsmL3Stack(tmsi=0)
    assert exc.value.code == g.INVALID_ARG and exc.value.message.strip() != ""

    # shard_count outside {0,4,8,16,32} is rejected by the wrapper before FFI
    base = _library.CALL_COUNTS.get("gsml3_registry_new", 0)
    with pytest.raises(ValueError):
        g.GsmL3Stack(tmsi=0x55555555, shard_count=3)
    assert _library.CALL_COUNTS.get("gsml3_registry_new", 0) == base

    # create_by_imsi is unsupported on sharded registries — C error, code UNSUPPORTED
    with pytest.raises(g.GsmL3Error) as exc:
        g.GsmL3Stack(imsi="244051234567890", shard_count=4)
    assert exc.value.code == g.UNSUPPORTED == 8

    # sending data before an established link: C error, last-error message non-empty
    with g.LapdmEntity(0) as e:
        e.open(sapi=0, command_bit=1)
        with pytest.raises(g.GsmL3Error) as exc2:
            e.send_data(b"\x50\x84")
        assert exc2.value.message.strip() != ""


def lapdm_decode_wrapper_validation():
    with pytest.raises(TypeError):
        g.lapdm_frame_decode(None)
    with pytest.raises(ValueError):
        g.lapdm_frame_decode(b"\x60")           # len < 2 before the FFI boundary


# ── Registry: sharded smoke + identity rules ───────────────────────────────

@pytest.mark.parametrize("shards", (4, 8, 16, 32))
def registry_sharded_smoke(shards):
    """Mirror of the C Concurrent-IndependentEntities test shape at the API
    level: 100 sessions per sharded registry flavor — create + find round trips
    and an exact count, all on the thread that created them (single-thread per
    handle contract; sharding is about cross-thread registry mediation)."""
    with g.Registry(shard_count=shards) as reg:
        for i in range(100):
            sess = reg.create_by_tmsi(0xA0000000 + shards * 1000 + i)
            assert reg.find_by_tmsi(0xA0000000 + shards * 1000 + i).tmsi == 0xA0000000 + shards * 1000 + i
        assert reg.count == 100


def registry_plain_identity_rules():
    """Duplicate keys raise GsmL3Error(DUPLICATE); an IMSI-created session on a
    PLAIN registry gets an auto-assigned TMSI and is findable by both keys."""
    with g.Registry(0) as reg:
        first = reg.create_by_tmsi(0x60000001)
        with pytest.raises(g.GsmL3Error) as exc:
            reg.create_by_tmsi(0x60000001)
        assert exc.value.code == g.DUPLICATE == 13

        by_imsi = reg.create_by_imsi("244051234567890")
        assert by_imsi.assigned_tmsi != 0          # auto-assigned key
        found = reg.find_by_imsi("244051234567890")
        assert found is not None and found.assigned_tmsi == by_imsi.assigned_tmsi
        found_by_key = reg.find_by_tmsi(by_imsi.assigned_tmsi)
        assert found_by_key is not None

        assert reg.remove(first) is True
        assert reg.find_by_tmsi(0x60000001) is None
    # closed registry: every accessor raises WITHOUT FFI
    with pytest.raises(g.ClosedGsmL3ObjectError):
        reg.create_by_tmsi(1)


def session_borrowed_after_registry_close():
    """A Session view must refuse to work after its owning registry is closed
    (borrowed handle — touching the raw pointer would be UB)."""
    with g.Registry(0) as reg:
        sess = reg.create_by_tmsi(0x70000001)
    # the registry is closed now — the borrowed view must refuse every access
    # (raising instead of touching a freed C handle is the whole point)
    with pytest.raises(g.ClosedGsmL3ObjectError):
        sess.tmsi


# -- Queue hygiene of the unified send path ---------------------------------

def test_tx_frames_produced_between_calls_are_never_lost():
    """A T200 retransmission captured by tick_t200 must survive a later
    send_frame() and remain retrievable through drain_tx_frames(): calls that
    return frames for one input never consume frames of an earlier operation."""
    with g.GsmL3Stack(tmsi=0x66000001, auto_response=False) as stack:
        stack.lapdm_entity.send_sabme()
        assert stack.drain_tx_frames() == [bytes([0x09, 0x2F])]   # first SABME taken out

        assert stack.tick_t200(900) == 1      # retransmitted SABME captured, still undrained

        l3 = g.build_cm_service_request(1, g.ID_TMSI, 0x66000001, None)
        txs = stack.send_frame(g.lapdm_mini.ui(0, False, l3))      # manual mode: emits nothing for this input
        assert txs == []

        assert stack.drain_tx_frames() == [bytes([0x09, 0x2F])]    # retransmission intact


def test_auto_response_batch_survives_a_failed_event():
    """In auto mode a GsmL3Error raised for ONE queued event — at any step:
    parse, feed, response build or transmission — is recorded in
    last_event_error; every remaining event of the same batch still gets its
    turn and none of them is dropped."""
    stack = g.GsmL3Stack(tmsi=0x66000002, auto_response=True)
    try:
        l3 = g.build_cm_service_request(1, g.ID_TMSI, 0x66000002, None)
        # Three pre-queued events + the one receive() will append => batch of 4.
        for _ in range(3):
            stack._l3_events.append(g.L3Event(sapi=0, primitive=g.PRIM_L3_UNIT_DATA, data=l3))

        orch = stack.orchestrator
        state = {"feeds": 0, "builds": 0}
        real_feed = orch.feed

        def counting_feed(msg, session=None):
            state["feeds"] += 1
            return real_feed(msg, session)

        def failing_build(session=None):
            state["builds"] += 1
            raise g.InvalidArgument(1, "simulated missing ResponseContext parameter")

        orch.feed = counting_feed
        orch.build_response = failing_build
        try:
            txs = stack.send_frame(g.lapdm_mini.ui(0, False, l3))   # must not raise
        finally:
            del orch.feed               # back to the class-level methods
            del orch.build_response

        assert state["feeds"] == 4          # all four events of the batch were attempted
        assert state["builds"] >= 1         # at least the first event reached response build
        assert txs == []                    # every response build failed: nothing transmitted
        assert stack.last_event_error is not None
        assert "simulated" in stack.last_event_error.message
        assert stack.drain_l3_events() == []    # the batch was fully consumed, none left behind
    finally:
        stack.close()


def test_component_accessors_and_dead_component_fail_fast():
    """Components are reachable through read-only accessors. If a component is
    closed out from under an open stack, every stack method raises
    ClosedGsmL3ObjectError immediately instead of silently no-op-ing on dead C
    handles; the stack teardown stays idempotent afterwards."""
    stack = g.GsmL3Stack(tmsi=0x66000004)
    try:
        assert isinstance(stack.registry, g.Registry)
        assert stack.session.tmsi == 0x66000004
        assert isinstance(stack.orchestrator, g.Orchestrator)
        assert isinstance(stack.lapdm_entity, g.LapdmEntity)

        l3 = g.build_cm_service_request(1, g.ID_TMSI, 0x66000004, None)
        stack.orchestrator.close()         # a component dies while the stack is open
        with pytest.raises(g.ClosedGsmL3ObjectError):
            stack.send_frame(g.lapdm_mini.ui(0, False, l3))
        with pytest.raises(g.ClosedGsmL3ObjectError):
            stack.tick_procedures(1)
        with pytest.raises(g.ClosedGsmL3ObjectError):
            stack.chain_phase
    finally:
        stack.close()                      # teardown must still work exactly once
        stack.close()                      # ...and remain a no-op afterwards
